name: update fork

on:
   workflow_dispatch:
   schedule:
     - cron: '30 11 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.WORKFLOW_TOKEN }}
    - name: Set env
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Update fork master
      run: |
        git remote add upstream https://github.com/shinchiro/mpv-winbuild-cmake.git
        git remote -v
        git fetch upstream
        git checkout master
        git rebase --strategy-option=ours upstream/master
        #git rebase --onto 8380365c3b3a8af6263900003851b3138a16af9e^ 8380365c3b3a8af6263900003851b3138a16af9e 2>/dev/null || true
        git push -f origin master
